function arte() {
    console.log("Arte-Cine")
    console.log("Primera Pelicula")
    var pelicula1 = new Cine("Pelicula:" + " El arca perdiada, " + "pelicual de " + " aventura, " + "su duracion es de " + " 1h ")
    pelicula1.atributos()
    console.log("Segunda Pelicula")
    var pelicula2 = new Cine("Pelucula:" + "The avengers, " + "pelicual de " + " accion " + "su duracion es de " + "2:23h")
    pelicula2.atributos()
    console.log("Arte-Escultura")
    console.log("Primera Escultura")
    var Estatua1 = new Escultura("Escultrua:" + " Venus de Milo " + "Echa de " + "Marmol " + "en el " + "130 a.C")
    Estatua1.atributos()
    console.log("Segunda Escultura")
    var Estatua2 = new Escultura("Escultrua:" + " El David" + " Echa de " + "Marmol " + "en el " + "1501")
    Estatua2.atributos()
    console.log("Arte-Pintura")
    console.log("Primer Cuadro")
    var cuadro1 = new Pintura("Cuadro:" + " La noche estrellada " + "pintado por " + "Vicente van gogh" + " la cual representa una " + "pintura del paisaje")
    cuadro1.atributos()
    console.log("Segundo Cuadro")
    var cuadro2 = new Pintura("Cuadro:" + " Guernica " + "pintado por " + "Pablo Picasso" + " el cual representa una obra " + "subrrealista")
    cuadro2.atributos()
    console.log("Arte-Teatro")
    console.log("Primera Obra")
    var actuacion1 = new Teatro("Obra:" + " Romeo y Julieta" + " que fue escrita por " + "William Shakespeare" + " en el " + "1597")
    actuacion1.atributos()
    console.log("Segunda Obra")
    var actuacion2 = new Teatro("Obra:" + " Hamlet" + " que fue escrita por " + "William Shakespeare" + " en el " + "1609")
    actuacion2.atributos()
}
arte()
